<?php

namespace Jet\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuscriberRepository extends EntityRepository
{
}