CoreLocalBundle:
    resource: "@CoreLocalBundle/Controller/"
    type:     annotation
    prefix:   /

CoreUserCtlBundle:
    resource: "@CoreUserBundle/Controller/"
    type:     annotation
    prefix:   /
   
RoleAdminBundle:
    resource: "@RoleAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
   
RoleUserBundle:
    resource: "@RoleUserBundle/Controller/"
    type:     annotation
    prefix:   /secured

CoreFoursquareBundle:
    resource: "@CoreFoursquareBundle/Controller/"
    type:     annotation
    prefix:   /

CoreUserBundle:
    resource: "@CoreUserBundle/Resources/config/routing.yml"

CoreApiBundle:
    resource: "@CoreApiBundle/Controller/"
    type:     annotation
    prefix:   /api


CoreTemplateBundle:
    resource: "@CoreTemplateBundle/Controller/"
    type:     annotation
    prefix:   /
    
   
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
