CoreUserBundle:
    resource: "@CoreUserBundle/Controller/"
    type:     annotation
    prefix:   /profile

CoreTemplateBundle:
    resource: "@CoreTemplateBundle/Controller/"
    type:     annotation
    prefix:   /
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
